[package]
name = "kernel_core"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
path = "main.rs"
name = "kernel"
test = false
bench = false

[dependencies]
kernel_builtin.workspace = true
kernel_exceptions.workspace = true
kernel_cpu.workspace = true
kernel_arch.workspace = true
kernel_mm.workspace = true

fdt.workspace = true 
