[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
    "-C", "link-arg=-Tlinker.ld",
    "-C", "link-arg=--nmagic",
]
runner = "qemu-system-aarch64 -M virt,dumpdtb=/tmp/virt.dtb -cpu cortex-a72 -m 128M -nographic -kernel"
